#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue May 21 20:03:51 CEST 2024
# SW Build 4126759 on Thu Feb  8 23:52:05 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim seven_segment_display_behav -key {Behavioral:sim_1:Functional:seven_segment_display} -tclbatch seven_segment_display.tcl -log simulate.log"
xsim seven_segment_display_behav -key {Behavioral:sim_1:Functional:seven_segment_display} -tclbatch seven_segment_display.tcl -log simulate.log

